#!/bin/bash

GUI="$1"

if [ "$GUI" == "gui" ]; then
	CMD=$([[ $TERMINAL == "alacritty" ]] && echo "-e $0" || echo "$0")

	$TERMINAL --hold --class "kill-process" $CMD
	exit
fi

SCRIPTS_DIR="$HOME/.config/hypr/scripts"

SELECTED="$(command find $SCRIPTS_DIR | \
	prune-dirs | \
	map basename | \
	cut -d'.' -f1 | \
	fzf --header "Pick a Script:")"

if [[ -n $SELECTED ]]; then
	ACTION=$(echo -e "Run\nEdit" | fzf --header "Choose an Action:")

	LINK_PATH=$(which $SELECTED)
	SCRIPT_REAL_PATH=$(realpath $LINK_PATH)

	if [ "$ACTION" == "Run" ]; then
		exec "$SCRIPT_REAL_PATH"
	fi
	
	exec "$EDITOR" "$SCRIPT_REAL_PATH"
fi

