#!/bin/bash

CONFIG="$HOME/.config/hypr/swaync/config.json"
STYLE="$HOME/.config/hypr/swaync/style.css"

CONFIG_FILES="$CONFIG $STYLE"

trap "killall swaync; exit" ERR EXIT

while true; do
	swaync -c ${CONFIG} -s ${STYLE} &
	inotifywait -e create,modify $CONFIG_FILES	
	killall swaync
done

