#!/bin/bash

VKD3D_CONFIG="dxr,dxr11"
PROTON_HIDE_NVIDIA_GPU="0"
RADV_PERFTEST="rt"

exec env VKD3D_CONFIG="${VKD3D_CONFIG}"\
	PROTON_HIDE_NVIDIA_GPU="${PROTON_HIDE_NVIDIA_GPU}"\
	RADV_PERFTEST=${RADV_PERFTEST}\
	nice -n -20 gamescope --adaptive-sync --hdr-enabled -h 1440 -r 468 gamemoderun "$@"

