#!/bin/bash

LOCK_TIMEOUT=300
MONITOR_TIMEOUT=900

swayidle -w \
	timeout "$LOCK_TIMEOUT" "swaylock -i $WALLPAPER"
	timeout "$MONITOR_TIMEOUT" "hyprctl dispatch dpms off" \
	resume "hyprctl dispatch dpms on"

