#!/bin/bash

SELF="$0"
GUI="$1"

if [ "$GUI" == "gui" ]; then
	CMD=$([[ $TERMINAL == "alacritty" ]] && echo "-e $0" || echo "$0")

	$TERMINAL --class "kill-process" $CMD
	exit
fi

SELECTED="$(ps --user $USER -F | \
	tail -n +2 | \
	awk '{print $2" "$11" "$12}' | \
	fzf --header "Pick a Process to Kill:")"

if [[ -n $SELECTED ]]; then
	ANSWER="$(echo -e "No\nYes" | fzf --header "Kill $SELECTED?")"
	
	if [[ $ANSWER == "Yes" ]]; then
		kill -9 "${SELECTED%% *}"
		notify-send "Process $SELECTED has been killed." && exit 0
		exit
	fi
	
	notify-send "User choose not to kill a process." && exit 1
fi

