#!/bin/bash

CONFIG="$HOME/.config/hypr/mako/config"

CONFIG_FILES="$CONFIG"

trap "killall mako" EXIT

while true; do
	mako --config ${CONFIG} &
	inotifywait -e create,modify $CONFIG_FILES	
	killall mako
done

