#!/bin/bash

SELF="$0"

SELF_SCRIPT_NAME=$(echo ${SELF##*/})

GUI="$1"

if [ "$GUI" == "gui" ]; then
	CMD=$([[ $TERMINAL == "alacritty" ]] && echo "-e $0" || echo "$0")

	$TERMINAL --class "kill-process" $CMD
	exit
fi

SCRIPTS_DIR="$HOME/.config/hypr/scripts"

SELECTED="$(command ls $SCRIPTS_DIR | \
	cut -d'.' -f1 | \
	grep -v "$SELF_SCRIPT_NAME" | \
	fzf --header "Pick a Script:")"

if [[ -n $SELECTED ]]; then
	ACTION=$(echo -e "Run\nEdit" | fzf --header "Choose an Action:")

	if [ "$ACTION" == "Run" ]; then
		exec "$SELECTED"
		exit
	fi
	
	LINK_PATH=$(which $SELECTED)
	SCRIPT_REAL_PATH=$(realpath $LINK_PATH)

	CMD=$([[ $TERMINAL == "alacritty" ]] &&\
		echo "-e $EDITOR $SCRIPT_REAL_PATH" || echo "$EDITOR $SCRIPT_REAL_PATH")
	cd $(dirname $SCRIPT_REAL_PATH)
	exec $CMD
fi

