#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkconfig &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Polkit
/usr/lib/polkit-kde-authentication-agent-1 &

# Hyprpaper
${SCRIPTSDIR}/wallpaper &

# Nextcloud
nextcloud --background &

# Blueman Applet
blueman-applet &

# KDE Connect
/usr/lib/kdeconnectd &
kdeconnect-indicator &

# PlayerCTLD
playerctld daemon &

# XWaylandPrimary
${SCRIPTSDIR}/xwayland-config &

# Replace Right Super with Home
xmodmap -e 'keycode 134 = Home'

