#!/bin/bash

# Hyprpaper
wallpaper &

# Lauch statusbar (waybar)
statusbar &

# Apply themes
gtkconfig &

# Lauch notification daemon (swaync)
notifications &

udiskie &

# Polkit
/usr/lib/polkit-kde-authentication-agent-1 &

# Idle Management
idle &

# Nextcloud Native:
start-file-sync &

# Easy Effects Service
easyeffects --gapplication-service &

# Nextcloud Snap:
#nextcloud-desktop-client.nextcloud --background &

# Blueman Applet
#blueman-applet &

# KDE Connect
/usr/lib/kdeconnectd &
kdeconnect-indicator &

# PlayerCTLD
playerctld daemon &

# XWaylandPrimary
xwayland-config &

# Bitwarden
bitwarden-desktop &

