#!/bin/bash

SCRIPTS_DIR="$HOME/.config/hypr/scripts"
TARGET_DIR="/usr/bin"

SCRIPTS=$(find $SCRIPTS_DIR | xargs)
IFS=" " read -ra SCRIPT <<< "$SCRIPTS"
for script in "${SCRIPT[@]}"; do
	if [ ! "$SCRIPTS_DIR" = "$script" ]; then
		SCRIPT_NAME=$(echo ${script##*/})
		SCRIPT_NAME_NO_EXT=$(echo $SCRIPT_NAME | cut -d'.' -f1)
		LINK_TARGET="$TARGET_DIR/$SCRIPT_NAME_NO_EXT"
		echo "Removing current link: $LINK_TARGET"
		sudo rm "$LINK_TARGET" 2> /dev/null
		echo "Creating new link for: $script"
		sudo ln -s "$script" "$LINK_TARGET"
	fi
done

